<?php

namespace App\AdminModule\Presenters;

use App\Model\Menu;
use App\Model\Roles;
use App\Presenters\BasePresenter;

class BaseAdminPresenter extends BasePresenter
{

    protected $redirectLogin = true;

    public function str_contains($haystack, $needle): bool
    {
        return $needle !== '' && mb_strpos($haystack, $needle) !== false;
    }

    protected function startup()
    {

        $this->getUser()->setAuthorizator(new Roles());

        if (!$this->user->isLoggedIn() && !in_array($this->presenter->getName(), ['Sign'])) {

            $this->flashMessage('Debes iniciar sesión primero');

            $this->redirect(':Sign:in');
        }

        parent::startup(); // TODO: Change the autogenerated stub

        $this->template->menu = Menu::getMenu($this->getUser());
        $this->template->rol = $this->getDbUser()->rol;
    }
}
